# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T12:41:21+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field, RootModel, conint


class AccessType(Enum):
    S3_SIGV4 = 'S3_SIGV4'
    SECRETS_MANAGER_ACCESS_TOKEN = 'SECRETS_MANAGER_ACCESS_TOKEN'


class BadRequestException(RootModel[Any]):
    root: Any


class ChannelState(Enum):
    RUNNING = 'RUNNING'
    STOPPED = 'STOPPED'


class DeleteChannelPolicyRequest(BaseModel):
    pass


class DeleteChannelPolicyResponse(BaseModel):
    pass


class DeleteChannelRequest(BaseModel):
    pass


class DeleteChannelResponse(BaseModel):
    pass


class DeleteLiveSourceRequest(BaseModel):
    pass


class DeleteLiveSourceResponse(BaseModel):
    pass


class DeletePlaybackConfigurationRequest(BaseModel):
    pass


class DeletePlaybackConfigurationResponse(BaseModel):
    pass


class DeletePrefetchScheduleRequest(BaseModel):
    pass


class DeletePrefetchScheduleResponse(BaseModel):
    pass


class DeleteProgramRequest(BaseModel):
    pass


class DeleteProgramResponse(BaseModel):
    pass


class DeleteSourceLocationRequest(BaseModel):
    pass


class DeleteSourceLocationResponse(BaseModel):
    pass


class DeleteVodSourceRequest(BaseModel):
    pass


class DeleteVodSourceResponse(BaseModel):
    pass


class DescribeChannelRequest(BaseModel):
    pass


class DescribeLiveSourceRequest(BaseModel):
    pass


class DescribeProgramRequest(BaseModel):
    pass


class DescribeSourceLocationRequest(BaseModel):
    pass


class DescribeVodSourceRequest(BaseModel):
    pass


class GetChannelPolicyRequest(BaseModel):
    pass


class GetChannelScheduleRequest(BaseModel):
    pass


class GetPlaybackConfigurationRequest(BaseModel):
    pass


class GetPrefetchScheduleRequest(BaseModel):
    pass


class Integer(RootModel[int]):
    root: int


class ListAlertsRequest(BaseModel):
    pass


class ListChannelsRequest(BaseModel):
    pass


class ListLiveSourcesRequest(BaseModel):
    pass


class ListPlaybackConfigurationsRequest(BaseModel):
    pass


class ListSourceLocationsRequest(BaseModel):
    pass


class ListTagsForResourceRequest(BaseModel):
    pass


class ListVodSourcesRequest(BaseModel):
    pass


class LogType(Enum):
    AS_RUN = 'AS_RUN'


class LogTypes(RootModel[List[LogType]]):
    root: List[LogType]


class Long(RootModel[int]):
    root: int


class MaxResults(RootModel[conint(ge=1, le=100)]):
    root: conint(ge=1, le=100)


class MessageType(Enum):
    SPLICE_INSERT = 'SPLICE_INSERT'
    TIME_SIGNAL = 'TIME_SIGNAL'


class Mode(Enum):
    OFF = 'OFF'
    BEHIND_LIVE_EDGE = 'BEHIND_LIVE_EDGE'


class Operator(Enum):
    EQUALS = 'EQUALS'


class OriginManifestType(Enum):
    SINGLE_PERIOD = 'SINGLE_PERIOD'
    MULTI_PERIOD = 'MULTI_PERIOD'


class PlaybackMode(Enum):
    LOOP = 'LOOP'
    LINEAR = 'LINEAR'


class PutChannelPolicyResponse(BaseModel):
    pass


class RelativePosition(Enum):
    BEFORE_PROGRAM = 'BEFORE_PROGRAM'
    AFTER_PROGRAM = 'AFTER_PROGRAM'


class ScheduleEntryType(Enum):
    PROGRAM = 'PROGRAM'
    FILLER_SLATE = 'FILLER_SLATE'


class StartChannelRequest(BaseModel):
    pass


class StartChannelResponse(BaseModel):
    pass


class StopChannelRequest(BaseModel):
    pass


class StopChannelResponse(BaseModel):
    pass


class String(RootModel[str]):
    root: str


class Tier(Enum):
    BASIC = 'BASIC'
    STANDARD = 'STANDARD'


class Type(Enum):
    DASH = 'DASH'
    HLS = 'HLS'


class UntagResourceRequest(BaseModel):
    pass


class FieldBoolean(RootModel[bool]):
    root: bool


class FieldInteger(RootModel[int]):
    root: int


class FieldIntegerMin1(RootModel[conint(ge=1)]):
    root: conint(ge=1)


class FieldIntegerMin1Max100(RootModel[conint(ge=1, le=100)]):
    root: conint(ge=1, le=100)


class FieldLong(RootModel[int]):
    root: int


class FieldString(RootModel[str]):
    root: str


class FieldTimestampUnix(RootModel[datetime]):
    root: datetime


class FillerSlate(BaseModel):
    SourceLocationName: Optional[FieldString] = None
    VodSourceName: Optional[FieldString] = None


class ChannelChannelNamePolicyPutRequest(BaseModel):
    Policy: str = Field(
        ...,
        description='Adds an IAM role that determines the permissions of your channel.',
    )


class ConfigureLogsChannelPutRequest(BaseModel):
    ChannelName: str = Field(..., description='The name of the channel.')
    LogTypes: List[LogType] = Field(..., description='The types of logs to collect.')


class ConfigureLogsPlaybackConfigurationPutRequest(BaseModel):
    PercentEnabled: int = Field(
        ...,
        description='<p>The percentage of session logs that MediaTailor sends to your Cloudwatch Logs account. For example, if your playback configuration has 1000 sessions and percentEnabled is set to <code>60</code>, MediaTailor sends logs for 600 of the sessions to CloudWatch Logs. MediaTailor decides at random which of the playback configuration sessions to send logs for. If you want to view logs for a specific session, you can use the <a href="https://docs.aws.amazon.com/mediatailor/latest/ug/debug-log-mode.html">debug log mode</a>.</p> <p>Valid values: <code>0</code> - <code>100</code> </p>',
    )
    PlaybackConfigurationName: str = Field(
        ..., description='The name of the playback configuration.'
    )


class AvailSuppression(BaseModel):
    Mode_1: Optional[Mode] = Field(None, alias='Mode')
    Value: Optional[FieldString] = None


class Bumper(BaseModel):
    EndUrl: Optional[FieldString] = None
    StartUrl: Optional[FieldString] = None


class CdnConfiguration(BaseModel):
    AdSegmentUrlPrefix: Optional[FieldString] = None
    ContentSegmentUrlPrefix: Optional[FieldString] = None


class DashConfiguration1(BaseModel):
    MpdLocation: Optional[FieldString] = None
    OriginManifestType_1: Optional[OriginManifestType] = Field(
        None, alias='OriginManifestType'
    )


class LivePreRollConfiguration(BaseModel):
    AdDecisionServerUrl: Optional[FieldString] = None
    MaxDurationSeconds: Optional[FieldInteger] = None


class PrefetchSchedulePlaybackConfigurationNamePostRequest(BaseModel):
    MaxResults: Optional[conint(ge=1, le=100)] = Field(
        None,
        description='The maximum number of prefetch schedules that you want MediaTailor to return in response to the current request. If there are more than <code>MaxResults</code> prefetch schedules, use the value of <code>NextToken</code> in the response to get the next page of results.',
    )
    NextToken: Optional[str] = Field(
        None,
        description="<p>(Optional) If the playback configuration has more than <code>MaxResults</code> prefetch schedules, use <code>NextToken</code> to get the second and subsequent pages of results.</p> <p> For the first <code>ListPrefetchSchedulesRequest</code> request, omit this value.</p> <p> For the second and subsequent requests, get the value of <code>NextToken</code> from the previous response and specify that value for <code>NextToken</code> in the request.</p> <p> If the previous response didn't include a <code>NextToken</code> element, there are no more prefetch schedules to get.</p>",
    )
    StreamId: Optional[str] = Field(
        None,
        description='An optional filtering parameter whereby MediaTailor filters the prefetch schedules to include only specific streams.',
    )


class DefaultSegmentDeliveryConfiguration(BaseModel):
    BaseUrl: Optional[FieldString] = None


class HttpConfiguration1(BaseModel):
    BaseUrl: Optional[FieldString] = None


class TagsResourceArnPostRequest(BaseModel):
    tags: Dict[str, FieldString] = Field(
        ...,
        description='The tags to assign to the resource. Tags are key-value pairs that you can associate with Amazon resources to help with organization, access control, and cost tracking. For more information, see <a href="https://docs.aws.amazon.com/mediatailor/latest/ug/tagging.html">Tagging AWS Elemental MediaTailor Resources</a>.',
    )


class TagKeys(RootModel[List[FieldString]]):
    root: List[FieldString]


class AdMarkerPassthrough(BaseModel):
    Enabled: Optional[FieldBoolean] = None


class AvailMatchingCriteria(BaseModel):
    DynamicVariable: FieldString
    Operator_1: Operator = Field(..., alias='Operator')


class ClipRange(BaseModel):
    EndOffsetMillis: FieldLong


class ConfigureLogsForChannelRequest(BaseModel):
    ChannelName: FieldString
    LogTypes_1: LogTypes = Field(..., alias='LogTypes')


class ConfigureLogsForChannelResponse(BaseModel):
    ChannelName: Optional[FieldString] = None
    LogTypes_1: Optional[LogTypes] = Field(None, alias='LogTypes')


class ConfigureLogsForPlaybackConfigurationRequest(BaseModel):
    PercentEnabled: FieldInteger
    PlaybackConfigurationName: FieldString


class ConfigureLogsForPlaybackConfigurationResponse(BaseModel):
    PercentEnabled: FieldInteger
    PlaybackConfigurationName: Optional[FieldString] = None


class DashConfiguration(BaseModel):
    ManifestEndpointPrefix: Optional[FieldString] = None
    MpdLocation: Optional[FieldString] = None
    OriginManifestType_1: Optional[OriginManifestType] = Field(
        None, alias='OriginManifestType'
    )


class DashConfigurationForPut(BaseModel):
    MpdLocation: Optional[FieldString] = None
    OriginManifestType_1: Optional[OriginManifestType] = Field(
        None, alias='OriginManifestType'
    )


class DashPlaylistSettings(BaseModel):
    ManifestWindowSeconds: Optional[FieldInteger] = None
    MinBufferTimeSeconds: Optional[FieldInteger] = None
    MinUpdatePeriodSeconds: Optional[FieldInteger] = None
    SuggestedPresentationDelaySeconds: Optional[FieldInteger] = None


class GetChannelPolicyResponse(BaseModel):
    Policy: Optional[FieldString] = None


class HlsConfiguration(BaseModel):
    ManifestEndpointPrefix: Optional[FieldString] = None


class HlsPlaylistSettings(BaseModel):
    ManifestWindowSeconds: Optional[FieldInteger] = None


class HttpConfiguration(BaseModel):
    BaseUrl: FieldString


class HttpPackageConfiguration(BaseModel):
    Path: FieldString
    SourceGroup: FieldString
    Type_1: Type = Field(..., alias='Type')


class HttpPackageConfigurations(RootModel[List[HttpPackageConfiguration]]):
    root: List[HttpPackageConfiguration] = Field(
        ..., description="The VOD source's HTTP package configuration settings."
    )


class ListPrefetchSchedulesRequest(BaseModel):
    MaxResults: Optional[FieldIntegerMin1Max100] = None
    NextToken: Optional[FieldString] = None
    StreamId: Optional[FieldString] = None


class LogConfiguration(BaseModel):
    PercentEnabled: FieldInteger


class LogConfigurationForChannel(BaseModel):
    LogTypes_1: Optional[LogTypes] = Field(None, alias='LogTypes')


class ManifestProcessingRules(BaseModel):
    AdMarkerPassthrough_1: Optional[AdMarkerPassthrough] = Field(
        None, alias='AdMarkerPassthrough'
    )


class PutChannelPolicyRequest(BaseModel):
    Policy: FieldString


class RequestOutputItem(BaseModel):
    DashPlaylistSettings_1: Optional[DashPlaylistSettings] = Field(
        None, alias='DashPlaylistSettings'
    )
    HlsPlaylistSettings_1: Optional[HlsPlaylistSettings] = Field(
        None, alias='HlsPlaylistSettings'
    )
    ManifestName: FieldString
    SourceGroup: FieldString


class RequestOutputs(RootModel[List[RequestOutputItem]]):
    root: List[RequestOutputItem] = Field(
        ...,
        description='An object that represents an object in the CreateChannel request.',
    )


class ResponseOutputItem(BaseModel):
    DashPlaylistSettings_1: Optional[DashPlaylistSettings] = Field(
        None, alias='DashPlaylistSettings'
    )
    HlsPlaylistSettings_1: Optional[HlsPlaylistSettings] = Field(
        None, alias='HlsPlaylistSettings'
    )
    ManifestName: FieldString
    PlaybackUrl: FieldString
    SourceGroup: FieldString


class ResponseOutputs(RootModel[List[ResponseOutputItem]]):
    root: List[ResponseOutputItem]


class ScheduleAdBreak(BaseModel):
    ApproximateDurationSeconds: Optional[FieldLong] = None
    ApproximateStartTime: Optional[FieldTimestampUnix] = None
    SourceLocationName: Optional[FieldString] = None
    VodSourceName: Optional[FieldString] = None


class SecretsManagerAccessTokenConfiguration(BaseModel):
    HeaderName: Optional[FieldString] = None
    SecretArn: Optional[FieldString] = None
    SecretStringKey: Optional[FieldString] = None


class SegmentDeliveryConfiguration(BaseModel):
    BaseUrl: Optional[FieldString] = None
    Name: Optional[FieldString] = None


class SegmentationDescriptor(BaseModel):
    SegmentNum: Optional[Integer] = None
    SegmentationEventId: Optional[Integer] = None
    SegmentationTypeId: Optional[Integer] = None
    SegmentationUpid: Optional[String] = None
    SegmentationUpidType: Optional[Integer] = None
    SegmentsExpected: Optional[Integer] = None
    SubSegmentNum: Optional[Integer] = None
    SubSegmentsExpected: Optional[Integer] = None


class SegmentationDescriptorList(RootModel[List[SegmentationDescriptor]]):
    root: List[SegmentationDescriptor]


class SlateSource(BaseModel):
    SourceLocationName: Optional[FieldString] = None
    VodSourceName: Optional[FieldString] = None


class SpliceInsertMessage(BaseModel):
    AvailNum: Optional[FieldInteger] = None
    AvailsExpected: Optional[FieldInteger] = None
    SpliceEventId: Optional[FieldInteger] = None
    UniqueProgramId: Optional[FieldInteger] = None


class TimeSignalMessage(BaseModel):
    SegmentationDescriptors: Optional[SegmentationDescriptorList] = None


class Transition(BaseModel):
    DurationMillis: Optional[FieldLong] = None
    RelativePosition_1: RelativePosition = Field(..., alias='RelativePosition')
    RelativeProgram: Optional[FieldString] = None
    ScheduledStartTimeMillis: Optional[FieldLong] = None
    Type: FieldString


class UpdateChannelRequest(BaseModel):
    FillerSlate: Optional[SlateSource] = None
    Outputs: RequestOutputs


class UpdateLiveSourceRequest(BaseModel):
    HttpPackageConfigurations_1: HttpPackageConfigurations = Field(
        ..., alias='HttpPackageConfigurations'
    )


class UpdateProgramTransition(BaseModel):
    DurationMillis: Optional[FieldLong] = None
    ScheduledStartTimeMillis: Optional[FieldLong] = None


class UpdateVodSourceRequest(BaseModel):
    HttpPackageConfigurations_1: HttpPackageConfigurations = Field(
        ..., alias='HttpPackageConfigurations'
    )


class FieldListOfAvailMatchingCriteria(RootModel[List[AvailMatchingCriteria]]):
    root: List[AvailMatchingCriteria]


class FieldListOfScheduleAdBreak(RootModel[List[ScheduleAdBreak]]):
    root: List[ScheduleAdBreak]


class FieldListOfSegmentDeliveryConfiguration(
    RootModel[List[SegmentDeliveryConfiguration]]
):
    root: List[SegmentDeliveryConfiguration]


class FieldListOfString(RootModel[List[FieldString]]):
    root: List[FieldString]


class FieldMapOfString(RootModel[Optional[Dict[str, FieldString]]]):
    root: Optional[Dict[str, FieldString]] = None


class ChannelChannelNamePostRequest(BaseModel):
    FillerSlate_1: Optional[FillerSlate] = Field(
        None, alias='FillerSlate', description='Slate VOD source configuration.'
    )
    Outputs: List[RequestOutputItem] = Field(
        ...,
        description='An object that represents an object in the CreateChannel request.',
    )
    PlaybackMode_1: PlaybackMode = Field(
        ...,
        alias='PlaybackMode',
        description='<p>The type of playback mode to use for this channel.</p> <p> <code>LINEAR</code> - The programs in the schedule play once back-to-back in the schedule.</p> <p> <code>LOOP</code> - The programs in the schedule play back-to-back in an endless loop. When the last program in the schedule stops playing, playback loops back to the first program in the schedule.</p>',
    )
    Tier_1: Optional[Tier] = Field(
        None, alias='Tier', description='The tier of the channel.'
    )
    tags: Optional[Dict[str, FieldString]] = Field(
        None,
        description='The tags to assign to the channel. Tags are key-value pairs that you can associate with Amazon resources to help with organization, access control, and cost tracking. For more information, see <a href="https://docs.aws.amazon.com/mediatailor/latest/ug/tagging.html">Tagging AWS Elemental MediaTailor Resources</a>.',
    )


class ChannelChannelNamePutRequest(BaseModel):
    FillerSlate_1: Optional[FillerSlate] = Field(
        None, alias='FillerSlate', description='Slate VOD source configuration.'
    )
    Outputs: List[RequestOutputItem] = Field(
        ...,
        description='An object that represents an object in the CreateChannel request.',
    )


class ScheduleConfiguration1(BaseModel):
    ClipRange_1: Optional[ClipRange] = Field(None, alias='ClipRange')
    Transition_1: Optional[Transition] = Field(None, alias='Transition')


class ScheduleConfiguration2(BaseModel):
    ClipRange_1: Optional[ClipRange] = Field(None, alias='ClipRange')
    Transition: Optional[UpdateProgramTransition] = None


class PlaybackConfigurationPutRequest(BaseModel):
    AdDecisionServerUrl: Optional[str] = Field(
        None,
        description='The URL for the ad decision server (ADS). This includes the specification of static parameters and placeholders for dynamic parameters. AWS Elemental MediaTailor substitutes player-specific and session-specific parameters as needed when calling the ADS. Alternately, for testing you can provide a static VAST URL. The maximum length is 25,000 characters.',
    )
    AvailSuppression_1: Optional[AvailSuppression] = Field(
        None,
        alias='AvailSuppression',
        description='The configuration for avail suppression, also known as ad suppression. For more information about ad suppression, see <a href="https://docs.aws.amazon.com/mediatailor/latest/ug/ad-behavior.html">Ad Suppression</a>.',
    )
    Bumper_1: Optional[Bumper] = Field(
        None,
        alias='Bumper',
        description='The configuration for bumpers. Bumpers are short audio or video clips that play at the start or before the end of an ad break. To learn more about bumpers, see <a href="https://docs.aws.amazon.com/mediatailor/latest/ug/bumpers.html">Bumpers</a>.',
    )
    CdnConfiguration_1: Optional[CdnConfiguration] = Field(
        None,
        alias='CdnConfiguration',
        description='The configuration for using a content delivery network (CDN), like Amazon CloudFront, for content and ad segment management.',
    )
    ConfigurationAliases: Optional[Dict[str, FieldMapOfString]] = Field(
        None, description='The predefined aliases for dynamic variables.'
    )
    DashConfiguration: Optional[DashConfiguration1] = Field(
        None, description='The configuration for DASH PUT operations.'
    )
    LivePreRollConfiguration_1: Optional[LivePreRollConfiguration] = Field(
        None,
        alias='LivePreRollConfiguration',
        description='The configuration for pre-roll ad insertion.',
    )
    ManifestProcessingRules_1: Optional[ManifestProcessingRules] = Field(
        None,
        alias='ManifestProcessingRules',
        description='The configuration for manifest processing rules. Manifest processing rules enable customization of the personalized manifests created by MediaTailor.',
    )
    Name: str = Field(..., description='The identifier for the playback configuration.')
    PersonalizationThresholdSeconds: Optional[conint(ge=1)] = Field(
        None,
        description='Defines the maximum duration of underfilled ad time (in seconds) allowed in an ad break. If the duration of underfilled ad time exceeds the personalization threshold, then the personalization of the ad break is abandoned and the underlying content is shown. This feature applies to <i>ad replacement</i> in live and VOD streams, rather than ad insertion, because it relies on an underlying content stream. For more information about ad break behavior, including ad replacement and insertion, see <a href="https://docs.aws.amazon.com/mediatailor/latest/ug/ad-behavior.html">Ad Behavior in AWS Elemental MediaTailor</a>.',
    )
    SlateAdUrl: Optional[str] = Field(
        None,
        description="The URL for a high-quality video asset to transcode and use to fill in time that's not used by ads. AWS Elemental MediaTailor shows the slate to fill in gaps in media content. Configuring the slate is optional for non-VPAID configurations. For VPAID, the slate is required because MediaTailor provides it in the slots that are designated for dynamic ad content. The slate must be a high-quality asset that contains both audio and video.",
    )
    TranscodeProfileName: Optional[str] = Field(
        None,
        description='The name that is used to associate this playback configuration with a custom transcode profile. This overrides the dynamic transcoding defaults of MediaTailor. Use this only if you have already set up custom profiles with the help of AWS Support.',
    )
    VideoContentSourceUrl: Optional[str] = Field(
        None,
        description='The URL prefix for the parent manifest for the stream, minus the asset ID. The maximum length is 512 characters.',
    )
    tags: Optional[Dict[str, FieldString]] = Field(
        None,
        description='The tags to assign to the playback configuration. Tags are key-value pairs that you can associate with Amazon resources to help with organization, access control, and cost tracking. For more information, see <a href="https://docs.aws.amazon.com/mediatailor/latest/ug/tagging.html">Tagging AWS Elemental MediaTailor Resources</a>.',
    )


class Consumption(BaseModel):
    AvailMatchingCriteria: Optional[FieldListOfAvailMatchingCriteria] = None
    EndTime: Optional[FieldTimestampUnix] = None
    StartTime: Optional[FieldTimestampUnix] = None


class Retrieval(BaseModel):
    DynamicVariables: Optional[FieldMapOfString] = None
    EndTime: Optional[FieldTimestampUnix] = None
    StartTime: Optional[FieldTimestampUnix] = None


class PrefetchSchedulePlaybackConfigurationNameNamePostRequest(BaseModel):
    Consumption_1: Consumption = Field(
        ...,
        alias='Consumption',
        description='A complex type that contains settings that determine how and when that MediaTailor places prefetched ads into upcoming ad breaks.',
    )
    Retrieval_1: Retrieval = Field(
        ...,
        alias='Retrieval',
        description='A complex type that contains settings governing when MediaTailor prefetches ads, and which dynamic variables that MediaTailor includes in the request to the ad decision server.',
    )
    StreamId: Optional[str] = Field(
        None,
        description='An optional stream identifier that MediaTailor uses to prefetch ads for multiple streams that use the same playback configuration. If <code>StreamId</code> is specified, MediaTailor returns all of the prefetch schedules with an exact match on <code>StreamId</code>. If not specified, MediaTailor returns all of the prefetch schedules for the playback configuration, regardless of <code>StreamId</code>.',
    )


class AccessConfiguration(BaseModel):
    AccessType_1: Optional[AccessType] = Field(None, alias='AccessType')
    SecretsManagerAccessTokenConfiguration_1: Optional[
        SecretsManagerAccessTokenConfiguration
    ] = Field(None, alias='SecretsManagerAccessTokenConfiguration')


class SourceLocationSourceLocationNamePostRequest(BaseModel):
    AccessConfiguration_1: Optional[AccessConfiguration] = Field(
        None,
        alias='AccessConfiguration',
        description='Access configuration parameters.',
    )
    DefaultSegmentDeliveryConfiguration_1: Optional[
        DefaultSegmentDeliveryConfiguration
    ] = Field(
        None,
        alias='DefaultSegmentDeliveryConfiguration',
        description="The optional configuration for a server that serves segments. Use this if you want the segment delivery server to be different from the source location server. For example, you can configure your source location server to be an origination server, such as MediaPackage, and the segment delivery server to be a content delivery network (CDN), such as CloudFront. If you don't specify a segment delivery server, then the source location server is used.",
    )
    HttpConfiguration: HttpConfiguration1 = Field(
        ..., description='The HTTP configuration for the source location.'
    )
    SegmentDeliveryConfigurations: Optional[List[SegmentDeliveryConfiguration]] = Field(
        None,
        description='A list of the segment delivery configurations associated with this resource.',
    )
    tags: Optional[Dict[str, FieldString]] = Field(
        None,
        description='The tags to assign to the source location. Tags are key-value pairs that you can associate with Amazon resources to help with organization, access control, and cost tracking. For more information, see <a href="https://docs.aws.amazon.com/mediatailor/latest/ug/tagging.html">Tagging AWS Elemental MediaTailor Resources</a>.',
    )


class SourceLocationSourceLocationNamePutRequest(BaseModel):
    AccessConfiguration_1: Optional[AccessConfiguration] = Field(
        None,
        alias='AccessConfiguration',
        description='Access configuration parameters.',
    )
    DefaultSegmentDeliveryConfiguration_1: Optional[
        DefaultSegmentDeliveryConfiguration
    ] = Field(
        None,
        alias='DefaultSegmentDeliveryConfiguration',
        description="The optional configuration for a server that serves segments. Use this if you want the segment delivery server to be different from the source location server. For example, you can configure your source location server to be an origination server, such as MediaPackage, and the segment delivery server to be a content delivery network (CDN), such as CloudFront. If you don't specify a segment delivery server, then the source location server is used.",
    )
    HttpConfiguration: HttpConfiguration1 = Field(
        ..., description='The HTTP configuration for the source location.'
    )
    SegmentDeliveryConfigurations: Optional[List[SegmentDeliveryConfiguration]] = Field(
        None,
        description='A list of the segment delivery configurations associated with this resource.',
    )


class SourceLocationSourceLocationNameLiveSourceLiveSourceNamePostRequest(BaseModel):
    HttpPackageConfigurations: List[HttpPackageConfiguration] = Field(
        ..., description="The VOD source's HTTP package configuration settings."
    )
    tags: Optional[Dict[str, FieldString]] = Field(
        None,
        description='The tags to assign to the live source. Tags are key-value pairs that you can associate with Amazon resources to help with organization, access control, and cost tracking. For more information, see <a href="https://docs.aws.amazon.com/mediatailor/latest/ug/tagging.html">Tagging AWS Elemental MediaTailor Resources</a>.',
    )


class SourceLocationSourceLocationNameLiveSourceLiveSourceNamePutRequest(BaseModel):
    HttpPackageConfigurations: List[HttpPackageConfiguration] = Field(
        ..., description="The VOD source's HTTP package configuration settings."
    )


class SourceLocationSourceLocationNameVodSourceVodSourceNamePostRequest(BaseModel):
    HttpPackageConfigurations: List[HttpPackageConfiguration] = Field(
        ..., description="The VOD source's HTTP package configuration settings."
    )
    tags: Optional[Dict[str, FieldString]] = Field(
        None,
        description='The tags to assign to the VOD source. Tags are key-value pairs that you can associate with Amazon resources to help with organization, access control, and cost tracking. For more information, see <a href="https://docs.aws.amazon.com/mediatailor/latest/ug/tagging.html">Tagging AWS Elemental MediaTailor Resources</a>.',
    )


class SourceLocationSourceLocationNameVodSourceVodSourceNamePutRequest(BaseModel):
    HttpPackageConfigurations: List[HttpPackageConfiguration] = Field(
        ..., description="The VOD source's HTTP package configuration settings."
    )


class AdBreak(BaseModel):
    MessageType_1: Optional[MessageType] = Field(None, alias='MessageType')
    OffsetMillis: Optional[FieldLong] = None
    Slate: Optional[SlateSource] = None
    SpliceInsertMessage_1: Optional[SpliceInsertMessage] = Field(
        None, alias='SpliceInsertMessage'
    )
    TimeSignalMessage_1: Optional[TimeSignalMessage] = Field(
        None, alias='TimeSignalMessage'
    )


class Alert(BaseModel):
    AlertCode: FieldString
    AlertMessage: FieldString
    LastModifiedTime: FieldTimestampUnix
    RelatedResourceArns: FieldListOfString
    ResourceArn: FieldString


class Channel(BaseModel):
    Arn: FieldString
    ChannelName: FieldString
    ChannelState: FieldString
    CreationTime: Optional[FieldTimestampUnix] = None
    FillerSlate: Optional[SlateSource] = None
    LastModifiedTime: Optional[FieldTimestampUnix] = None
    LogConfiguration: LogConfigurationForChannel
    Outputs: ResponseOutputs
    PlaybackMode: FieldString
    Tags: Optional[FieldMapOfString] = None
    Tier: FieldString


class ConfigurationAliasesRequest(RootModel[Optional[Dict[str, FieldMapOfString]]]):
    root: Optional[Dict[str, FieldMapOfString]] = None


class ConfigurationAliasesResponse(RootModel[Optional[Dict[str, FieldMapOfString]]]):
    root: Optional[Dict[str, FieldMapOfString]] = None


class CreateChannelRequest(BaseModel):
    FillerSlate: Optional[SlateSource] = None
    Outputs: RequestOutputs
    PlaybackMode_1: PlaybackMode = Field(..., alias='PlaybackMode')
    Tags: Optional[FieldMapOfString] = None
    Tier_1: Optional[Tier] = Field(None, alias='Tier')


class CreateChannelResponse(BaseModel):
    Arn: Optional[FieldString] = None
    ChannelName: Optional[FieldString] = None
    ChannelState_1: Optional[ChannelState] = Field(None, alias='ChannelState')
    CreationTime: Optional[FieldTimestampUnix] = None
    FillerSlate: Optional[SlateSource] = None
    LastModifiedTime: Optional[FieldTimestampUnix] = None
    Outputs: Optional[ResponseOutputs] = None
    PlaybackMode: Optional[FieldString] = None
    Tags: Optional[FieldMapOfString] = None
    Tier: Optional[FieldString] = None


class CreateLiveSourceRequest(BaseModel):
    HttpPackageConfigurations_1: HttpPackageConfigurations = Field(
        ..., alias='HttpPackageConfigurations'
    )
    Tags: Optional[FieldMapOfString] = None


class CreateLiveSourceResponse(BaseModel):
    Arn: Optional[FieldString] = None
    CreationTime: Optional[FieldTimestampUnix] = None
    HttpPackageConfigurations_1: Optional[HttpPackageConfigurations] = Field(
        None, alias='HttpPackageConfigurations'
    )
    LastModifiedTime: Optional[FieldTimestampUnix] = None
    LiveSourceName: Optional[FieldString] = None
    SourceLocationName: Optional[FieldString] = None
    Tags: Optional[FieldMapOfString] = None


class CreateSourceLocationRequest(BaseModel):
    AccessConfiguration_1: Optional[AccessConfiguration] = Field(
        None, alias='AccessConfiguration'
    )
    DefaultSegmentDeliveryConfiguration_1: Optional[
        DefaultSegmentDeliveryConfiguration
    ] = Field(None, alias='DefaultSegmentDeliveryConfiguration')
    HttpConfiguration_1: HttpConfiguration = Field(..., alias='HttpConfiguration')
    SegmentDeliveryConfigurations: Optional[FieldListOfSegmentDeliveryConfiguration] = (
        None
    )
    Tags: Optional[FieldMapOfString] = None


class CreateSourceLocationResponse(BaseModel):
    AccessConfiguration_1: Optional[AccessConfiguration] = Field(
        None, alias='AccessConfiguration'
    )
    Arn: Optional[FieldString] = None
    CreationTime: Optional[FieldTimestampUnix] = None
    DefaultSegmentDeliveryConfiguration_1: Optional[
        DefaultSegmentDeliveryConfiguration
    ] = Field(None, alias='DefaultSegmentDeliveryConfiguration')
    HttpConfiguration_1: Optional[HttpConfiguration] = Field(
        None, alias='HttpConfiguration'
    )
    LastModifiedTime: Optional[FieldTimestampUnix] = None
    SegmentDeliveryConfigurations: Optional[FieldListOfSegmentDeliveryConfiguration] = (
        None
    )
    SourceLocationName: Optional[FieldString] = None
    Tags: Optional[FieldMapOfString] = None


class CreateVodSourceRequest(BaseModel):
    HttpPackageConfigurations_1: HttpPackageConfigurations = Field(
        ..., alias='HttpPackageConfigurations'
    )
    Tags: Optional[FieldMapOfString] = None


class CreateVodSourceResponse(BaseModel):
    Arn: Optional[FieldString] = None
    CreationTime: Optional[FieldTimestampUnix] = None
    HttpPackageConfigurations_1: Optional[HttpPackageConfigurations] = Field(
        None, alias='HttpPackageConfigurations'
    )
    LastModifiedTime: Optional[FieldTimestampUnix] = None
    SourceLocationName: Optional[FieldString] = None
    Tags: Optional[FieldMapOfString] = None
    VodSourceName: Optional[FieldString] = None


class DescribeChannelResponse(BaseModel):
    Arn: Optional[FieldString] = None
    ChannelName: Optional[FieldString] = None
    ChannelState_1: Optional[ChannelState] = Field(None, alias='ChannelState')
    CreationTime: Optional[FieldTimestampUnix] = None
    FillerSlate: Optional[SlateSource] = None
    LastModifiedTime: Optional[FieldTimestampUnix] = None
    LogConfiguration: LogConfigurationForChannel
    Outputs: Optional[ResponseOutputs] = None
    PlaybackMode: Optional[FieldString] = None
    Tags: Optional[FieldMapOfString] = None
    Tier: Optional[FieldString] = None


class DescribeLiveSourceResponse(BaseModel):
    Arn: Optional[FieldString] = None
    CreationTime: Optional[FieldTimestampUnix] = None
    HttpPackageConfigurations_1: Optional[HttpPackageConfigurations] = Field(
        None, alias='HttpPackageConfigurations'
    )
    LastModifiedTime: Optional[FieldTimestampUnix] = None
    LiveSourceName: Optional[FieldString] = None
    SourceLocationName: Optional[FieldString] = None
    Tags: Optional[FieldMapOfString] = None


class DescribeSourceLocationResponse(BaseModel):
    AccessConfiguration_1: Optional[AccessConfiguration] = Field(
        None, alias='AccessConfiguration'
    )
    Arn: Optional[FieldString] = None
    CreationTime: Optional[FieldTimestampUnix] = None
    DefaultSegmentDeliveryConfiguration_1: Optional[
        DefaultSegmentDeliveryConfiguration
    ] = Field(None, alias='DefaultSegmentDeliveryConfiguration')
    HttpConfiguration_1: Optional[HttpConfiguration] = Field(
        None, alias='HttpConfiguration'
    )
    LastModifiedTime: Optional[FieldTimestampUnix] = None
    SegmentDeliveryConfigurations: Optional[FieldListOfSegmentDeliveryConfiguration] = (
        None
    )
    SourceLocationName: Optional[FieldString] = None
    Tags: Optional[FieldMapOfString] = None


class DescribeVodSourceResponse(BaseModel):
    Arn: Optional[FieldString] = None
    CreationTime: Optional[FieldTimestampUnix] = None
    HttpPackageConfigurations_1: Optional[HttpPackageConfigurations] = Field(
        None, alias='HttpPackageConfigurations'
    )
    LastModifiedTime: Optional[FieldTimestampUnix] = None
    SourceLocationName: Optional[FieldString] = None
    Tags: Optional[FieldMapOfString] = None
    VodSourceName: Optional[FieldString] = None


class GetPlaybackConfigurationResponse(BaseModel):
    AdDecisionServerUrl: Optional[FieldString] = None
    AvailSuppression_1: Optional[AvailSuppression] = Field(
        None, alias='AvailSuppression'
    )
    Bumper_1: Optional[Bumper] = Field(None, alias='Bumper')
    CdnConfiguration_1: Optional[CdnConfiguration] = Field(
        None, alias='CdnConfiguration'
    )
    ConfigurationAliases: Optional[ConfigurationAliasesResponse] = None
    DashConfiguration_1: Optional[DashConfiguration] = Field(
        None, alias='DashConfiguration'
    )
    HlsConfiguration_1: Optional[HlsConfiguration] = Field(
        None, alias='HlsConfiguration'
    )
    LivePreRollConfiguration_1: Optional[LivePreRollConfiguration] = Field(
        None, alias='LivePreRollConfiguration'
    )
    LogConfiguration_1: Optional[LogConfiguration] = Field(
        None, alias='LogConfiguration'
    )
    ManifestProcessingRules_1: Optional[ManifestProcessingRules] = Field(
        None, alias='ManifestProcessingRules'
    )
    Name: Optional[FieldString] = None
    PersonalizationThresholdSeconds: Optional[FieldIntegerMin1] = None
    PlaybackConfigurationArn: Optional[FieldString] = None
    PlaybackEndpointPrefix: Optional[FieldString] = None
    SessionInitializationEndpointPrefix: Optional[FieldString] = None
    SlateAdUrl: Optional[FieldString] = None
    Tags: Optional[FieldMapOfString] = None
    TranscodeProfileName: Optional[FieldString] = None
    VideoContentSourceUrl: Optional[FieldString] = None


class ListTagsForResourceResponse(BaseModel):
    Tags: Optional[FieldMapOfString] = None


class LiveSource(BaseModel):
    Arn: FieldString
    CreationTime: Optional[FieldTimestampUnix] = None
    HttpPackageConfigurations_1: HttpPackageConfigurations = Field(
        ..., alias='HttpPackageConfigurations'
    )
    LastModifiedTime: Optional[FieldTimestampUnix] = None
    LiveSourceName: FieldString
    SourceLocationName: FieldString
    Tags: Optional[FieldMapOfString] = None


class PlaybackConfiguration(BaseModel):
    AdDecisionServerUrl: Optional[FieldString] = None
    AvailSuppression_1: Optional[AvailSuppression] = Field(
        None, alias='AvailSuppression'
    )
    Bumper_1: Optional[Bumper] = Field(None, alias='Bumper')
    CdnConfiguration_1: Optional[CdnConfiguration] = Field(
        None, alias='CdnConfiguration'
    )
    ConfigurationAliases: Optional[ConfigurationAliasesResponse] = None
    DashConfiguration_1: Optional[DashConfiguration] = Field(
        None, alias='DashConfiguration'
    )
    HlsConfiguration_1: Optional[HlsConfiguration] = Field(
        None, alias='HlsConfiguration'
    )
    LivePreRollConfiguration_1: Optional[LivePreRollConfiguration] = Field(
        None, alias='LivePreRollConfiguration'
    )
    LogConfiguration_1: Optional[LogConfiguration] = Field(
        None, alias='LogConfiguration'
    )
    ManifestProcessingRules_1: Optional[ManifestProcessingRules] = Field(
        None, alias='ManifestProcessingRules'
    )
    Name: Optional[FieldString] = None
    PersonalizationThresholdSeconds: Optional[FieldIntegerMin1] = None
    PlaybackConfigurationArn: Optional[FieldString] = None
    PlaybackEndpointPrefix: Optional[FieldString] = None
    SessionInitializationEndpointPrefix: Optional[FieldString] = None
    SlateAdUrl: Optional[FieldString] = None
    Tags: Optional[FieldMapOfString] = None
    TranscodeProfileName: Optional[FieldString] = None
    VideoContentSourceUrl: Optional[FieldString] = None


class PrefetchConsumption(BaseModel):
    AvailMatchingCriteria: Optional[FieldListOfAvailMatchingCriteria] = None
    EndTime: FieldTimestampUnix
    StartTime: Optional[FieldTimestampUnix] = None


class PrefetchRetrieval(BaseModel):
    DynamicVariables: Optional[FieldMapOfString] = None
    EndTime: FieldTimestampUnix
    StartTime: Optional[FieldTimestampUnix] = None


class PrefetchSchedule(BaseModel):
    Arn: FieldString
    Consumption: PrefetchConsumption
    Name: FieldString
    PlaybackConfigurationName: FieldString
    Retrieval: PrefetchRetrieval
    StreamId: Optional[FieldString] = None


class PutPlaybackConfigurationRequest(BaseModel):
    AdDecisionServerUrl: Optional[FieldString] = None
    AvailSuppression_1: Optional[AvailSuppression] = Field(
        None, alias='AvailSuppression'
    )
    Bumper_1: Optional[Bumper] = Field(None, alias='Bumper')
    CdnConfiguration_1: Optional[CdnConfiguration] = Field(
        None, alias='CdnConfiguration'
    )
    ConfigurationAliases: Optional[ConfigurationAliasesRequest] = None
    DashConfiguration: Optional[DashConfigurationForPut] = None
    LivePreRollConfiguration_1: Optional[LivePreRollConfiguration] = Field(
        None, alias='LivePreRollConfiguration'
    )
    ManifestProcessingRules_1: Optional[ManifestProcessingRules] = Field(
        None, alias='ManifestProcessingRules'
    )
    Name: FieldString
    PersonalizationThresholdSeconds: Optional[FieldIntegerMin1] = None
    SlateAdUrl: Optional[FieldString] = None
    Tags: Optional[FieldMapOfString] = None
    TranscodeProfileName: Optional[FieldString] = None
    VideoContentSourceUrl: Optional[FieldString] = None


class PutPlaybackConfigurationResponse(BaseModel):
    AdDecisionServerUrl: Optional[FieldString] = None
    AvailSuppression_1: Optional[AvailSuppression] = Field(
        None, alias='AvailSuppression'
    )
    Bumper_1: Optional[Bumper] = Field(None, alias='Bumper')
    CdnConfiguration_1: Optional[CdnConfiguration] = Field(
        None, alias='CdnConfiguration'
    )
    ConfigurationAliases: Optional[ConfigurationAliasesResponse] = None
    DashConfiguration_1: Optional[DashConfiguration] = Field(
        None, alias='DashConfiguration'
    )
    HlsConfiguration_1: Optional[HlsConfiguration] = Field(
        None, alias='HlsConfiguration'
    )
    LivePreRollConfiguration_1: Optional[LivePreRollConfiguration] = Field(
        None, alias='LivePreRollConfiguration'
    )
    LogConfiguration_1: Optional[LogConfiguration] = Field(
        None, alias='LogConfiguration'
    )
    ManifestProcessingRules_1: Optional[ManifestProcessingRules] = Field(
        None, alias='ManifestProcessingRules'
    )
    Name: Optional[FieldString] = None
    PersonalizationThresholdSeconds: Optional[FieldIntegerMin1] = None
    PlaybackConfigurationArn: Optional[FieldString] = None
    PlaybackEndpointPrefix: Optional[FieldString] = None
    SessionInitializationEndpointPrefix: Optional[FieldString] = None
    SlateAdUrl: Optional[FieldString] = None
    Tags: Optional[FieldMapOfString] = None
    TranscodeProfileName: Optional[FieldString] = None
    VideoContentSourceUrl: Optional[FieldString] = None


class ScheduleConfiguration(BaseModel):
    ClipRange_1: Optional[ClipRange] = Field(None, alias='ClipRange')
    Transition_1: Transition = Field(..., alias='Transition')


class ScheduleEntry(BaseModel):
    ApproximateDurationSeconds: Optional[FieldLong] = None
    ApproximateStartTime: Optional[FieldTimestampUnix] = None
    Arn: FieldString
    ChannelName: FieldString
    LiveSourceName: Optional[FieldString] = None
    ProgramName: FieldString
    ScheduleAdBreaks: Optional[FieldListOfScheduleAdBreak] = None
    ScheduleEntryType_1: Optional[ScheduleEntryType] = Field(
        None, alias='ScheduleEntryType'
    )
    SourceLocationName: FieldString
    VodSourceName: Optional[FieldString] = None


class SourceLocation(BaseModel):
    AccessConfiguration_1: Optional[AccessConfiguration] = Field(
        None, alias='AccessConfiguration'
    )
    Arn: FieldString
    CreationTime: Optional[FieldTimestampUnix] = None
    DefaultSegmentDeliveryConfiguration_1: Optional[
        DefaultSegmentDeliveryConfiguration
    ] = Field(None, alias='DefaultSegmentDeliveryConfiguration')
    HttpConfiguration_1: HttpConfiguration = Field(..., alias='HttpConfiguration')
    LastModifiedTime: Optional[FieldTimestampUnix] = None
    SegmentDeliveryConfigurations: Optional[FieldListOfSegmentDeliveryConfiguration] = (
        None
    )
    SourceLocationName: FieldString
    Tags: Optional[FieldMapOfString] = None


class TagResourceRequest(BaseModel):
    Tags: FieldMapOfString


class UpdateChannelResponse(BaseModel):
    Arn: Optional[FieldString] = None
    ChannelName: Optional[FieldString] = None
    ChannelState_1: Optional[ChannelState] = Field(None, alias='ChannelState')
    CreationTime: Optional[FieldTimestampUnix] = None
    FillerSlate: Optional[SlateSource] = None
    LastModifiedTime: Optional[FieldTimestampUnix] = None
    Outputs: Optional[ResponseOutputs] = None
    PlaybackMode: Optional[FieldString] = None
    Tags: Optional[FieldMapOfString] = None
    Tier: Optional[FieldString] = None


class UpdateLiveSourceResponse(BaseModel):
    Arn: Optional[FieldString] = None
    CreationTime: Optional[FieldTimestampUnix] = None
    HttpPackageConfigurations_1: Optional[HttpPackageConfigurations] = Field(
        None, alias='HttpPackageConfigurations'
    )
    LastModifiedTime: Optional[FieldTimestampUnix] = None
    LiveSourceName: Optional[FieldString] = None
    SourceLocationName: Optional[FieldString] = None
    Tags: Optional[FieldMapOfString] = None


class UpdateProgramScheduleConfiguration(BaseModel):
    ClipRange_1: Optional[ClipRange] = Field(None, alias='ClipRange')
    Transition: Optional[UpdateProgramTransition] = None


class UpdateSourceLocationRequest(BaseModel):
    AccessConfiguration_1: Optional[AccessConfiguration] = Field(
        None, alias='AccessConfiguration'
    )
    DefaultSegmentDeliveryConfiguration_1: Optional[
        DefaultSegmentDeliveryConfiguration
    ] = Field(None, alias='DefaultSegmentDeliveryConfiguration')
    HttpConfiguration_1: HttpConfiguration = Field(..., alias='HttpConfiguration')
    SegmentDeliveryConfigurations: Optional[FieldListOfSegmentDeliveryConfiguration] = (
        None
    )


class UpdateSourceLocationResponse(BaseModel):
    AccessConfiguration_1: Optional[AccessConfiguration] = Field(
        None, alias='AccessConfiguration'
    )
    Arn: Optional[FieldString] = None
    CreationTime: Optional[FieldTimestampUnix] = None
    DefaultSegmentDeliveryConfiguration_1: Optional[
        DefaultSegmentDeliveryConfiguration
    ] = Field(None, alias='DefaultSegmentDeliveryConfiguration')
    HttpConfiguration_1: Optional[HttpConfiguration] = Field(
        None, alias='HttpConfiguration'
    )
    LastModifiedTime: Optional[FieldTimestampUnix] = None
    SegmentDeliveryConfigurations: Optional[FieldListOfSegmentDeliveryConfiguration] = (
        None
    )
    SourceLocationName: Optional[FieldString] = None
    Tags: Optional[FieldMapOfString] = None


class UpdateVodSourceResponse(BaseModel):
    Arn: Optional[FieldString] = None
    CreationTime: Optional[FieldTimestampUnix] = None
    HttpPackageConfigurations_1: Optional[HttpPackageConfigurations] = Field(
        None, alias='HttpPackageConfigurations'
    )
    LastModifiedTime: Optional[FieldTimestampUnix] = None
    SourceLocationName: Optional[FieldString] = None
    Tags: Optional[FieldMapOfString] = None
    VodSourceName: Optional[FieldString] = None


class VodSource(BaseModel):
    Arn: FieldString
    CreationTime: Optional[FieldTimestampUnix] = None
    HttpPackageConfigurations_1: HttpPackageConfigurations = Field(
        ..., alias='HttpPackageConfigurations'
    )
    LastModifiedTime: Optional[FieldTimestampUnix] = None
    SourceLocationName: FieldString
    Tags: Optional[FieldMapOfString] = None
    VodSourceName: FieldString


class FieldListOfAdBreak(RootModel[List[AdBreak]]):
    root: List[AdBreak]


class FieldListOfAlert(RootModel[List[Alert]]):
    root: List[Alert]


class FieldListOfChannel(RootModel[List[Channel]]):
    root: List[Channel]


class FieldListOfLiveSource(RootModel[List[LiveSource]]):
    root: List[LiveSource]


class FieldListOfPlaybackConfiguration(RootModel[List[PlaybackConfiguration]]):
    root: List[PlaybackConfiguration]


class FieldListOfPrefetchSchedule(RootModel[List[PrefetchSchedule]]):
    root: List[PrefetchSchedule]


class FieldListOfScheduleEntry(RootModel[List[ScheduleEntry]]):
    root: List[ScheduleEntry]


class FieldListOfSourceLocation(RootModel[List[SourceLocation]]):
    root: List[SourceLocation]


class FieldListOfVodSource(RootModel[List[VodSource]]):
    root: List[VodSource]


class ChannelChannelNameProgramProgramNamePostRequest(BaseModel):
    AdBreaks: Optional[List[AdBreak]] = Field(
        None, description='The ad break configuration settings.'
    )
    LiveSourceName: Optional[str] = Field(
        None, description='The name of the LiveSource for this Program.'
    )
    ScheduleConfiguration: ScheduleConfiguration1 = Field(
        ...,
        description='Schedule configuration parameters. A channel must be stopped before changes can be made to the schedule.',
    )
    SourceLocationName: str = Field(..., description='The name of the source location.')
    VodSourceName: Optional[str] = Field(
        None, description="The name that's used to refer to a VOD source."
    )


class ChannelChannelNameProgramProgramNamePutRequest(BaseModel):
    AdBreaks: Optional[List[AdBreak]] = Field(
        None, description='The ad break configuration settings.'
    )
    ScheduleConfiguration: ScheduleConfiguration2 = Field(
        ..., description='Schedule configuration parameters.'
    )


class CreatePrefetchScheduleRequest(BaseModel):
    Consumption: PrefetchConsumption
    Retrieval: PrefetchRetrieval
    StreamId: Optional[FieldString] = None


class CreatePrefetchScheduleResponse(BaseModel):
    Arn: Optional[FieldString] = None
    Consumption: Optional[PrefetchConsumption] = None
    Name: Optional[FieldString] = None
    PlaybackConfigurationName: Optional[FieldString] = None
    Retrieval: Optional[PrefetchRetrieval] = None
    StreamId: Optional[FieldString] = None


class CreateProgramRequest(BaseModel):
    AdBreaks: Optional[FieldListOfAdBreak] = None
    LiveSourceName: Optional[FieldString] = None
    ScheduleConfiguration_1: ScheduleConfiguration = Field(
        ..., alias='ScheduleConfiguration'
    )
    SourceLocationName: FieldString
    VodSourceName: Optional[FieldString] = None


class CreateProgramResponse(BaseModel):
    AdBreaks: Optional[FieldListOfAdBreak] = None
    Arn: Optional[FieldString] = None
    ChannelName: Optional[FieldString] = None
    ClipRange_1: Optional[ClipRange] = Field(None, alias='ClipRange')
    CreationTime: Optional[FieldTimestampUnix] = None
    DurationMillis: Optional[FieldLong] = None
    LiveSourceName: Optional[FieldString] = None
    ProgramName: Optional[FieldString] = None
    ScheduledStartTime: Optional[FieldTimestampUnix] = None
    SourceLocationName: Optional[FieldString] = None
    VodSourceName: Optional[FieldString] = None


class DescribeProgramResponse(BaseModel):
    AdBreaks: Optional[FieldListOfAdBreak] = None
    Arn: Optional[FieldString] = None
    ChannelName: Optional[FieldString] = None
    ClipRange_1: Optional[ClipRange] = Field(None, alias='ClipRange')
    CreationTime: Optional[FieldTimestampUnix] = None
    DurationMillis: Optional[Long] = None
    LiveSourceName: Optional[FieldString] = None
    ProgramName: Optional[FieldString] = None
    ScheduledStartTime: Optional[FieldTimestampUnix] = None
    SourceLocationName: Optional[FieldString] = None
    VodSourceName: Optional[FieldString] = None


class GetChannelScheduleResponse(BaseModel):
    Items: Optional[FieldListOfScheduleEntry] = None
    NextToken: Optional[FieldString] = None


class GetPrefetchScheduleResponse(BaseModel):
    Arn: Optional[FieldString] = None
    Consumption: Optional[PrefetchConsumption] = None
    Name: Optional[FieldString] = None
    PlaybackConfigurationName: Optional[FieldString] = None
    Retrieval: Optional[PrefetchRetrieval] = None
    StreamId: Optional[FieldString] = None


class ListAlertsResponse(BaseModel):
    Items: Optional[FieldListOfAlert] = None
    NextToken: Optional[FieldString] = None


class ListChannelsResponse(BaseModel):
    Items: Optional[FieldListOfChannel] = None
    NextToken: Optional[FieldString] = None


class ListLiveSourcesResponse(BaseModel):
    Items: Optional[FieldListOfLiveSource] = None
    NextToken: Optional[FieldString] = None


class ListPlaybackConfigurationsResponse(BaseModel):
    Items: Optional[FieldListOfPlaybackConfiguration] = None
    NextToken: Optional[FieldString] = None


class ListPrefetchSchedulesResponse(BaseModel):
    Items: Optional[FieldListOfPrefetchSchedule] = None
    NextToken: Optional[FieldString] = None


class ListSourceLocationsResponse(BaseModel):
    Items: Optional[FieldListOfSourceLocation] = None
    NextToken: Optional[FieldString] = None


class ListVodSourcesResponse(BaseModel):
    Items: Optional[FieldListOfVodSource] = None
    NextToken: Optional[FieldString] = None


class UpdateProgramRequest(BaseModel):
    AdBreaks: Optional[FieldListOfAdBreak] = None
    ScheduleConfiguration: UpdateProgramScheduleConfiguration


class UpdateProgramResponse(BaseModel):
    AdBreaks: Optional[FieldListOfAdBreak] = None
    Arn: Optional[FieldString] = None
    ChannelName: Optional[FieldString] = None
    ClipRange_1: Optional[ClipRange] = Field(None, alias='ClipRange')
    CreationTime: Optional[FieldTimestampUnix] = None
    DurationMillis: Optional[FieldLong] = None
    LiveSourceName: Optional[FieldString] = None
    ProgramName: Optional[FieldString] = None
    ScheduledStartTime: Optional[FieldTimestampUnix] = None
    SourceLocationName: Optional[FieldString] = None
    VodSourceName: Optional[FieldString] = None
